### ISSUE TITLE
Comparing FDS files detects error also in case there are not

### ISSUE THREAD

**Issue by rupole1185** [CFD-FEA-SERVICE/blenderfds28x#1]
Run on all FDS files to detect false non equals file
@CarloPoletto -> if you can define which test didn't work

**Comment by CarloPoletto** [comment]
Until now I found two differences types. Below I report the compare between the original `tjunction.fds` (top) vs the exported one (bottom):

**First difference**

      &SURF ID='Material' RGB=204,204,204 TRANSPARENCY=1.00 /
      ---------------------------
      &SURF ID='Material'
            RGB=204,204,204
            TRANSPARENCY=1.00 /

**Second difference**

      ! XB: 84 voxels, resolution 0.005 m, in 0.865 s
      ---------------------------
      ! XB: 84 voxels, resolution 0.005 m, in 0.707 s

**Comment by rupole1185** [comment]
Actions:

1) Regenerate file tjunction.fds with newer blenderFDS version
2) Ignore comments lines

**Comment by rupole1185** [comment]
Fixed
