### ISSUE TITLE
Export 1 FDS case per scene

### ISSUE THREAD

**Issue by rupole1185** [CFD-FEA-SERVICE/blenderfds28x#12]
For the unit test BLENDER 2 FDS we want now to export 1 FDS file for each schene and, consequently, compare it to the right FDS file.

Comparison file is named after the scene name.

N.B.: this tasks include some ammends to the results XML file to be discussed.

**Comment by rupole1185** [comment]
For this case use the new voxelization test file in the repository

**Comment by CarloPoletto** [comment]
I'm not sure I understood how to choose the right FDS file. Briefly, tests using a .fds file are compared to the same .fds file (no change compared to now!):

- **input1.fds** -> input1.fds
- **input2.fds** -> input2.fds

Instead, the tests that use a .blend file as input are compared with a .fds file called as the selected scene (regardless of the .blend file name!!):

- **inputA.fds** (scene1) --> scene1.fds
- **inputA.fds** (scene2)  --> scene2.fds
- **inputB.fds** (scene3)  --> scene3.fds

Is it correct?

**Comment by rupole1185** [comment]
exactly!
